module.exports = {
  availableLoadsByCarrierId: '/api/v1/carriers/${carrierId}/loads/active',
  unbilledLoadsByCarrierId: '/api/v1/carriers/${carrierId}/loads/unbilled',
  upcomingLoadsByCarrierId: '/api/v1/carriers/${carrierId}/loads/upcoming',
  loadCountByCarrierId: '/api/v1/carriers/${carrierId}/loads/count',
  loadsBySearchText: '/api/v1/carriers/${carrierId}/loads/${searchText}',
  carriers: '/api/v1/carriers',
  carrierById: '/api/v1/carriers/${carrierId}',
  userById: '/api/v1/users/${userId}',
  deactivateUserById: '/api/v1/users/${userId}/deactivate',
  user: '/api/v1/users',
  signIn: '/api/v1/auth/signIn',
  signOut: '/api/v1/auth/signOut',
  refresh: '/api/v1/auth/refresh',
  createPassword: '/api/v1/users/${userId}/createPassword',
  repByCarrierId: '/api/v1/carriers/${carrierId}/echorep',
  portalUsers: '/api/v1/carriers/${carrierId}/portalusers',
  driverCount: '/api/v1/carriers/${carrierId}/drivers/count',
  drivers: '/api/v1/carriers/${carrierId}/drivers',
  driver: '/api/v1/users/drivers',
  driverById: '/api/v1/users/drivers/${driverId}',
  searchDrivers: '/api/v1/carriers/${carrierId}/drivers/${searchTerm}',
  portalUserById: '/api/v1/carriers/${carrierId}/portalusers/${userId}',
  language: '/api/v1/preferredLanguages',
  forgotPassword: '/api/v1/auth/forgotPassword',
  changePassword: '/api/v1/users/${userId}/setPassword'
};